Traceback (most recent call last):
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
end = int(end_date.timestamp()) # transforma fecha final unix-time a entero
start = int(start_date.timestamp())# transforma fecha inicial unix-time a entero

AAPL_res = finnhub_client.stock_candles(stock, resolution, start, end) #respuesta 
AAPL_df = pd.DataFrame(AAPL_res) # transformar respuesta  pandas

AAPL_df.head()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[6], line 2[0m
[0;32m      1[0m end [38;5;241m=[39m [38;5;28mint[39m(end_date[38;5;241m.[39mtimestamp()) [38;5;66;03m# transforma fecha final unix-time a entero[39;00m
[1;32m----> 2[0m start [38;5;241m=[39m [38;5;28mint[39m([43mstart_date[49m[38;5;241;43m.[39;49m[43mtimestamp[49m())[38;5;66;03m# transforma fecha inicial unix-time a entero[39;00m
[0;32m      4[0m AAPL_res [38;5;241m=[39m finnhub_client[38;5;241m.[39mstock_candles(stock, resolution, start, end) [38;5;66;03m#respuesta [39;00m
[0;32m      5[0m AAPL_df [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(AAPL_res) [38;5;66;03m# transformar respuesta  pandas[39;00m

[1;31mAttributeError[0m: 'int' object has no attribute 'timestamp'

